name: Deploy FinStreak API

on:
  push:
    branches: [ "master" ]

env:
  # Nome da imagem (minúsculo obrigatório)
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/finstreak-api:latest
  CONTAINER_NAME: finstreak-backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build com Maven (Gera o .jar)
        run: mvn clean package -DskipTests

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build e Push da Imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}

      - name: Deploy na VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Logando no Registry..."
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            echo "Baixando nova versão..."
            docker pull ${{ env.IMAGE_NAME }}
            
            echo "Parando container antigo..."
            docker stop ${{ env.CONTAINER_NAME }} || true
            docker rm ${{ env.CONTAINER_NAME }} || true
            
            echo "Subindo novo container..."
            # AQUI ESTÁ A MÁGICA DAS VARIÁVEIS DE AMBIENTE:
            docker run -d \
              --name ${{ env.CONTAINER_NAME }} \
              --network vps-network \
              --restart always \
              -p 8080:8080 \
              -e SERVER_PORT=8080 \
              -e DB_HOST=vps-postgres \
              -e DB_PORT=5432 \
              -e DB_NAME=finstreak \
              -e DB_USER=postgres \
              -e DB_PASS=${{ secrets.DB_PASS }} \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              ${{ env.IMAGE_NAME }}
            
            echo "Limpando a casa..."
            docker image prune -f